{- -----------------------------------------------------------------
 - Test Cases
 - -----------------------------------------------------------------
 -
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: 0.0 0.0 (\x -> 0) 0
 - - Expected Output: error
 - - Acutal Output: *** Exception: definiteIntegral only defined on positive partitions.
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: 0.0 0.0 (\x -> 0) 1
 - - Expected Output: 0.0
 - - Acutal Output: 0.0
 - -----------------------------------------------------------------
 - - Function: definiteIntegral 
 - - Test Case Number:
 - - Input: 0.0 1.0 (\x -> 1) 1
 - - Expected Output: 1.0
 - - Acutal Output: 1.0
 - -----------------------------------------------------------------
 - - Function: definiteIntegral 
 - - Test Case Number:
 - - Input: 0.0 1.0 (\x -> 1) 5
 - - Expected Output: 1.0
 - - Acutal Output: 1.0
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: (-1.5) (1.0) (\x -> 1) 1
 - - Expected Output: 2.5
 - - Acutal Output: 2.5
 - -----------------------------------------------------------------
 - - Function: definiteIntegral 
 - - Test Case Number:
 - - Input: 0.0 (-3.0) (\x -> x) 1
 - - Expected Output: 4.5
 - - Acutal Output: 4.5
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: (-3.0) 3.0 (\x -> x) 1
 - - Expected Output: 0.0
 - - Acutal Output: 0.0
 - -----------------------------------------------------------------
 - - Function: definiteIntegral 
 - - Test Case Number:
 - - Input: 0.0 4.0 (\x -> x^2) 1
 - - Expected Output: 32.0
 - - Acutal Output: 32.0
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: 0.0 4.0 (\x -> x^2) 10
 - - Expected Output: 21.4
 - - Acutal Output: 21.44000000000001
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: 0.0 4.0 (\x -> x^2) 100
 - - Expected Output: 21.3333
 - - Acutal Output: 21.3344
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: (-2.0) (-1.99) (\x -> x^4) 100
 - - Expected Output: 0.158408
 - - Acutal Output: 0.15840798041800344
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: 1.0 4.0 (\x -> (1/x)) 100
 - - Expected Output: 1.3863
 - - Acutal Output: 1.3863646668991465
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: 0.0 (pi/2) (\x -> sin x) 100
 - - Expected Output: 1.0
 - - Acutal Output: 0.9999794382396078
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: (-2*pi) (2*pi) (\x -> cos x) 100
 - - Expected Output: 0.0
 - - Acutal Output: 1.0824674490095276e-15
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: 1.0 7.0 (\x -> log x) 100
 - - Expected Output: 7.6214
 - - Acutal Output: 7.621113936388163
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: (-1.0) (-7.0) (\x -> log x) 100
 - - Expected Output: NaN
 - - Acutal Output: NaN
 - -----------------------------------------------------------------
 - - Function: definiteIntegral
 - - Test Case Number:
 - - Input: 0.004 71.04 (\x -> x^2 - log x + cos x) 1000
 - - Expected Output: 119275.0
 - - Acutal Output: 119274.6169754577
 - -----------------------------------------------------------------
 - -----------------------------------------------------------------
 - - Function: funH
 - - Test Case Number:
 - - Input: 0
 - - Expected Output: error
 - - Acutal Output: *** Exception: funH only defined on postive integers.
 - -----------------------------------------------------------------
 - - Function: funH
 - - Test Case Number: 
 - - Input: (-1)
 - - Expected Output: error
 - - Acutal Output: *** Exception: funH only defined on positive integers.
 - -----------------------------------------------------------------
 - - Function: funH
 - - Test Case Number: 
 - - Input: 1
 - - Expected Output: 0.0
 - - Acutal Output: 0.0
 - -----------------------------------------------------------------
 - - Function: funH
 - - Test Case Number:
 - - Input: 10
 - - Expected Output: 0.81818
 - - Acutal Output: 0.8179718838152743
 - -----------------------------------------------------------------
 - - Function: funH
 - - Test Case Number:
 - - Input: 63
 - - Expected Output: 0.96875
 - - Acutal Output: 0.9683095249716419
 - -----------------------------------------------------------------
 - - Function: funH
 - - Test Case Number:
 - - Input: 10000000
 - - Expected Output: 0.999999
 - - Acutal Output: 0.9989999004373001
 - -----------------------------------------------------------------
 - -----------------------------------------------------------------
 - - Function: funK
 - - Test Case Number:
 - - Input: 0
 - - Expected Output: error
 - - Acutal Output: *** Exception: funK only defined on positive numbers.
 - -----------------------------------------------------------------
 - - Function: funK
 - - Test Case Number:
 - - Input: (-1)
 - - Expected Output: error
 - - Acutal Output: *** Exception: funK only defined on positive numbers.
 - -----------------------------------------------------------------
 - - Function: funK
 - - Test Case Number:
 - - Input: 1.0
 - - Expected Output: 2.0
 - - Acutal Output: 2.0000000000000013
 - -----------------------------------------------------------------
 - - Function: funK
 - - Test Case Number:
 - - Input: 2.0
 - - Expected Output: 2.1640
 - - Acutal Output: 2.164042907907025
 - -----------------------------------------------------------------
 - - Function: funK
 - - Test Case Number:
 - - Input: 0.4
 - - Expected Output: 2.29185
 - - Acutal Output: 2.291849644071788
 - -----------------------------------------------------------------
 - - Function: funK
 - - Test Case Number:
 - - Input: 0.000001
 - - Expected Output: 72382.4
 - - Acutal Output: 72387.0187620579
 - -----------------------------------------------------------------
 - - Function: funK
 - - Test Case Number: 
 - - Input: 1000000.0
 - - Expected Output: 72382.4
 - - Acutal Output: 72387.0187620579
 - -----------------------------------------------------------------
 - End of Test Cases
 - -----------------------------------------------------------------
 - -----------------------------------------------------------------
 - QuickCheck Cases
 - -----------------------------------------------------------------
 - See Assign_5_Test.hs for QuickCheck propositions and cases.
 -}

